### ISSUE TITLE
SyntaxError: missing ) after argument list

### ISSUE THREAD

**Issue by erperejildo** [sheerun/knex-migrate#37]
Getting this error on Windows:

```
E:\Repositories\quandoo-api\node_modules\.bin\knex-migrate:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:656:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! express-typescript-starter@0.1.0 ts-node: `node -r ./node_modules/ts-node/register -r ./src/env "./node_modules/.bin/knex-migrate" "up"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the express-typescript-starter@0.1.0 ts-node script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by sheerun** [comment]
I don't think this script supports windows. Someone would need to rewrite it to node

**Comment by erperejildo** [comment]
I just fixed it removing `/.bin` from my task
